{% set name = "types-Routes" %}
{% set version = "0.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-Routes-{{ version }}.tar.gz
  sha256: c3680702981b1506524f281ef9c39a0b7fdef6ff15fcbf7a985e926cafb36cfb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/routes-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for Routes
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
